CGNS/CGNS

src/tools/cgnscheck.c
Removed semicolon which was rendering if statement to be ineffective.
=> Remove incorrect semicolon

src/cgnstools/utilities/p3dfout.c
Added missing closing paren for printf statement.
=> Add missing close paren.

src/ptests/benchmark_hdf5.c
This file was mostly correct in CGNS_ENUMV uses, but was missing a few.  Added those and it now works correctly with CGNS_SCOPE_ENUMS defined
=> Fix a few missing CGNS_ENUMV uses

src/ptests/benchmark_hdf5.c
=> Revert "Fix c_double_eq function"

src/CMakeLists.txt
Or else it is sensitive to BUILD_SHARED_LIBS cmake var
=> Specify STATIC when adding cgns_static lib

src/Test_UserGuideCode/C_code/read_flowcentrind_str.c, src/Test_UserGuideCode/Fortran_code/read_flowcentrind_str.F90, src/cgnslib.c, src/cgnslib.h, src/pcgnslib.c, src/pcgnslib.h
This pull request improves rind plane indexing for coordinates reading and writing.
pcgnslib is still a work in progress. Refactoring can be improved.
=> Rind plane indexing

src/cgns_internals.c, src/cgnslib.c
- remove a printf used for debug
- specify max string length to prevent buffer overflow in sprintf
=> remove some gcc warnings

src/cgns_internals.c
The data_type argument added to cgi_error call about unsupported datatype.
=> Add missing argument to cgi_error call

src/cgns_internals.c, src/pcgnslib.c, src/pcgnslib.h, src/ptests/CMakeLists.txt, src/ptests/Makefile.in, src/ptests/test_cgp_general_rind.c
In parallel writing mode NULL pointer can be used to write node without data
=> Fix parallel write

src/adfh/ADFH.c
The `data` pointer is never set to any value, so remains NULL throughout.  Remove all code inside `if (data != NULL)`
This removes all mentions of `data`, so remove its assignment also.
=> Eliminate dead / unreachable code

src/cgns_io.c, src/tests/ser_benchmark_hdf5.c
=> Revert " Fixed compliation error with cc: Sun C 5.12 SunOS_sparc"

src/tests/Makefile.in, src/tests/test_general_reshape.c, src/tests/test_general_rind.c
Added missing test for autotools
=> Fixed ENUMVS issue in tests

src/tests/test_general_reshape.c
Assert statement was assigning instead of checking for equality.
=> Fix bad assert

src/CMakeLists.txt
- Problems linking Fortran code with 3.3.1 shared library (w/ CMake)
=> FIX: CGNS-118

.travis.yml, src/CMakeLists.txt
Also installing mpich as prep for parallel testing.
=> Updated to testing on newer ubuntu 

.travis.yml, bin/build-cgns.sh, bin/config-cgns.sh, bin/install-hdf.sh
CGNS-134  --- Add compilation and parallel testing to CI for Linux
=> CGNS-134 (#1)

src/adfh/ADFH.c, src/cgns_internals.c, src/cgns_io.c, src/cgnslib.c, src/cgnstools/cgnsplot/cgnstcl.c, src/cgnstools/tkogl/tkoglparse.c, src/tests/test_bbox.c, src/tests/test_general_reshape.c, src/tests/write_test.c, src/tools/cgnames.c, src/tools/cgnscheck.c
Some compilation warning fix and coverity related fix
=> Coverity fix

CMakeLists.txt, appveyor.yml, src/Test_UserGuideCode/C_code/CMakeLists.txt, src/Test_UserGuideCode/C_code_parallel/CMakeLists.txt, src/cgnstools/cgnscalc/CMakeLists.txt, src/cgnstools/cgnsplot/CMakeLists.txt, src/cgnstools/cgnsview/CMakeLists.txt, src/cgnstools/utilities/CMakeLists.txt, src/tools/CMakeLists.txt
=> small cmake cleaning

src/configure, src/configure.ac
https://cgnsorg.atlassian.net/browse/CGNS-38
=> JIRA CGNS-38

src/cgns_internals.c, src/cgnslib.c
@brtnfld This small change fix the issue found by Dave Taflin
It could be backported to 4.1
=> missing offset suffix

CMakeLists.txt, src/cgns_internals.c, src/cgnslib.c, src/configure.ac, src/tools/cgnscheck.c
Update cmake to enable 64bit configuration by default.
=> ENABLE 64BIT by default

bin/config-cgns.sh, src/cgns_header.h, src/cgns_internals.c, src/configure
* update the configure to set default 64bit
* fix shadow variable
=> Improve maintainability

src/adfh/ADFH.c
H5Literate_by_name is not regression tested in HDF5, H5Literate is.
=> replaced the use of H5Literate_by_name with H5Literate

src/adfh/ADFH.h, src/cgnslib.c, src/pcgnslib.c, src/ptests/open_close.c, src/tests/open_cgns.c, src/tests/test_goto.c
Fixes false error returned from cg_configure and added error checks for cg_configure in the tests, CGNS-241.
=> CGNS-241, fixed cg_configure return value error

src/cgns_internals.c
The code of the function is simplified and still has a performance issue but it is mentionned clearly.
=> Add a warning to cgi_sort_names function

src/cgnslib.c
Put back lost changes from Greg Sjaardema
=> simplify check from CGNS-136

src/configure, src/configure.ac
Remove header checking for zlib and szip.
=> CGNS-233 Does configure.ac need to check for zlib/szip headers?

src/cgnstools/utilities/cgns_to_aflr3.c, src/cgnstools/utilities/update_ngon.c
conversion of FamilySpecified BC for AFLR3 file format, experimental support
=> Experimental conversion of FamilySpecified BC

src/ptests/test_poly_unstructured.c
Several missing macros to handle the scoping setting
=> Add some missing macros

src/cgnslib.c
ACCESS check is already done in cgio_check_file called by cgio_open_file.
=> Remove unneeded check

src/tools/cgnscheck.c
Basic test suggested by Beta CAE
=> Very basic detection of duplicate face indices in NFaces

src/tests/cgwrite_f03.F90
Missed this test in the PR #696
=> removed c_funloc test for cg_configure

src/cgns_header.h, src/cgns_internals.c
=> fix compiler warning

src/cg_ftoc.c, src/cgns_f.F90, src/cgns_header.h, src/cgns_internals.c, src/cgnslib.c, src/pcgnslib.c, src/pcgnslib.h, src/ptests/CMakeLists.txt, src/ptests/Makefile.in, src/ptests/test_unstruc_quad.c, src/ptests/test_unstruc_quad_f90.F90
Adding parallel writing functionality for `cg_boco_write`.
Closes #728
=> Add cgp_ptset_write/read functions

CMakeLists.txt
Set an installed rpath that handle install location different from "lib" for multiple arch support for instance.
=> Improve packaging

src/examples/fortran/Test_Family/OUTPUT, src/examples/fortran/Test_Family/cgwrite.F90
=> make example valid for cgnscheck 

CMakeLists.txt, src/CMakeLists.txt, src/cgns_internals.c, src/cgnstypes.h.in, src/configure, src/configure.ac, src/tools/cgnscheck.c
- define cgsize_t as a intxx_t type
- provide PRIdCGSIZE
- follow hdf5 changes according to #754
=> Fix issue #754

src/cgns_error.c, src/cgnslib.c, src/cgnslib.h, src/doxygen/doxygen.config, src/pcgnslib.c
Format clean-up added missing APIs.
It works with Breathe and Sphinx. There are still some issues with links to groups not showing up in Sphinx. I marked them in this PR and will address them in the Breathe and Sphinx PR.
=> Doxygen Updates

src/cgns_header.h, src/cgnslib.c, src/tools/cgnscheck.c
=> fixed missing ENUMV declarations

src/tests/test_particle.c
Additional missed CGNS_ENUMV from PR #767
=> fixed missing CGNS_ENUMV
