CGNS/CGNS

- src/CMakeLists.txt
Should be also fixed in 3.3.0-rc1
> Fix installation error when building without Fortran.

- CMakeLists.txt
Use a predefined CMake variable to specify the shared library suffix (.so vs .dylib) to facilitate building on MacOSX
> Support Mac's dylib shared library suffix

- src/cgnstypes.h.in
- src/configure.bat
The problem is that the incorrect _stat_ implementation was used; instead of `_stat32i64` it defaults to `_stat64i32` (VS2010/x64). By re-defining _stat_ to `_stat32i64` in cgnstypes.h (that is, in the CMake .in file and in the configure.bat file), this problem is solved and files larger than 2^32-1 bytes can be opened.
> Fixes for CGNS-83: Large files fail on 64-bit windows

- src/cgnstools/utilities/CMakeLists.txt
binaryio.c is needed to resolve bf_machname symbol referenced from OPENF in p3dfout.c
> Add missing dependency in cgns_to_plot3d (cmake build)

- src/cgnstools/utilities/cgnsutil.c
The conversion from double to real was accessing an incorrect array -- dataconv instead of exponent.  This was also causing invalid memory accesses.  Looks like cut/paste error using code from line 1731 and not updating the structure field being accessed.
> Fix incorrect structured field array access -- cut paste error

- src/cgns_io.c
Should free link_file instead of link_name.  Other frees are correct.
> Freeing incorrect pointer

- src/ptests/benchmark_hdf5.c
The c_double_eq function needs an absolute value of the difference.  The current test of "a-b < eps" will return true whenever a is less than b.  For example, c_double_eq(1,10) will return true since 1-10 == -9 which is less than eps.  
Function could also be shortened to "return (fabs(a-b) < eps);"
> Fix c_double_eq function

- src/cgnstools/cgnsview/CMakeLists.txt
Added missing opengl_include_dir path to include_directories.
With the current hdf5 find_package, it doesn't seem like HDF5_LIBRARY is defined and the link dependency is specified earlier on the CGNS library itself, so removed HDF5_LIBRARY from the test and the link library.  
With these changes (and other pull requests), this builds in both shared and static mode on a Mac.
> Add missing include path, fix hdf5

- src/pcgnslib.c
If this zone has no elements on this processor, then it must still call `cgp_elements_read_data` or `cgp_elements_write_data` in order for the collectives down in the HDF5 library to work correctly (calls an MPI_Allreduce and possibly other collectives). Therefore, only check for valid data range if the 'elements' pointer is non-null.
This is similar to what is done in `cgp_coord_write_data` and `cgp_coord_read_data` at lines 369 and 320.
> Fix to avoid hang due to collective requirement

- src/tools/cgnscheck.c
Looks like code in section above was copy/pasted, but not all z's updated to dz's
(found by coverity)
> Copy-paste error

- src/cgns_io.c
err is possibly used unintialized in test "if(err == set_error(CGIO_ERR_NONE)) return err;" around line 618.  
At line 582, fp is checked and if it is NULL, then error codes are set.  However, execution then falls out of the if NULL test and then fp is used in the fread function at line 589.  It looks like there should maybe be a "return err" at the end of the NULL test.
(Both of these found by coverity)
> Initialize err, add missing return

- src/pcgnslib.c
If wbuf or rbuf are NULL, then `H5Screate_simple` is still called, but `dims` was not being initialized.
> Handle case where wbuf or rbuf is NULL

- src/adfh/ADFH.c
ADFH_Configure did not set error code if option was ADFH_CONFIG_MPI_COMM.
Note that I set it to NO_ERROR to follow guidance of the ADFH_CONFIG_COMPRESS branch, but NO_ERROR seems to be different from CG_OK.  Should successful return be CG_OK or NO_ERROR?
The return value of ADFH_Configure is returned unchanged from cgp_mpi_comm, so cgp_mpi_comm is returning a -1 instead of CG_OK.
> Error code was not set correctly.

- src/cgnstools/common/hash.c
- src/tools/hash.c
This corrects spelling mistake in `HashStats()` function in two different files. I discovered this while trying to use the function but got linker errors.
PS: This same file is present in **two** different directories. Code should be modified to use one of those & delete the other file. This will help code maintenance. I can send another pull request for that change if that change is desired.
> Spelling error in function name

- src/CMakeLists.txt
Determine which fortran concatenation macro to use in a CMake-based build.
Checks whether the a##b mode works; if not, then assumes that the IDENTITY(a)b mode works.
This is used in cgnstypes_f03.h
> Check for Fortran concatenation setting in CMake

- src/configure.bat
- src/pcgnslib.c
- src/pcgnslib.h
- src/ptests/CMakeLists.txt
- src/ptests/Makefile.in
- src/ptests/test_unstruc_quad.c
A first shot at an implementation for cgp_parent_data_write. It works in the testing I have done on my local project, but not sure if the "style" is correct. It currently uses an MPI_Allreduce call to determine the total size of the ParentElements and ParentElementsPosition nodes which are created during the function. It might be cleaner to have two functions -- one to create the nodes and one to write the data to the nodes, but this implementation follows the behavior of the serial version.
There is a test that writes a 2D unstructured mesh and puts a BC on bottom and left side.
Let me know what you think and I will modify as needed.
> Implementation and test for cgp_parent_data_write

- src/cgns_io.c
- src/pcgnslib.c
cgp_open now uses current communicator, defined by cgp_mpi_comm.
Hi, I ran into CGNS-85 also in the case of a MPMD program where rank 0 in MPI_COMM_WORLD was not involved in opening the file.
Here is the fix I propose, similar to the one described in the CGNS-85 issue. 
Basically, the communicator used when calling cgp_mpi_comm is saved and reused for cgp_open and cgio_check_file.
> CGNS-85 fix,

- CMakeLists.txt
- src/CMakeLists.txt
- src/cg_malloc.c
- src/cgnslib.c
This PR permits the control of the memory debugging capability via cmake.  To enable, define CGNS_ENABLE_MEM_DEBUG=ON.
The address storing in cg_malloc did not seem to work correctly; perhaps an issue with sequence points, so separated the `*data++ = (size_t)(data + 1);` into two lines: `*data = (size_t)(data + 1);` and `data++;`
Slight modification to the memory debug output:
* Added "CGNS MEM_DEBUG" prefix to the output lines in cg_open and cg_close.
* Added output of the number of alloc and free calls.
> Add cmake support for memory debugging; fix memory debug routines

- src/CMakeLists.txt
- src/adf/ADF.h
- src/adf/adf_ftoc.c
- src/adfh/ADFH.h
- src/adfh/ADFH_ftoc.c
- src/cgio_ftoc.c
- src/cgns_header.h
- src/cgns_io.h
- src/cgnslib.h
- src/tools/CMakeLists.txt
Fixes mingw build:
- declspec keyword typo, xref https://msdn.microsoft.com/fr-fr/library/3y1sfaz2(v=vs.100).aspx
- install dll in bin in a simpler manner ; as the dll prefix is different on mingw we should avoid hardwire the dll name
> Fix Windows build

- src/cgns_internals.c
For unstructured mesh, mesh_dim = {nnode,nelem}, the multiply product
of mesh_dim may be exceed the limit of 32-bit integer. We don't need
check the product actually but the component of mesh_dim.
> Modified by zbhfut <zhangbing_end@163.com>, 2017-11-09

- src/pcgnslib.c
If a processor has no data to write, then the start and end values passed in are sometimes arbitrary from calling code.  For example end > start or end == start.  Depending on the values, there can be logic errors in the following code.  To avoid this, set start = end = 0 if a processor has no data to output (section->parelem == NULL).
> If processor has no data, set end = start = 0

- src/cgnstools/cgnscalc/calcwish.c
- src/cgnstools/cgnsplot/plotwish.c
- src/cgnstools/cgnsview/cgiowish.c
- src/cgnstools/tkogl/tkAppInit.c
See https://wiki.tcl.tk/3577
Also, matherr has been removed from glibc since 2.27, see http://man7.org/linux/man-pages/man3/matherr.3.html.
> Drop obsolete matherr hack

- src/cgnslib.c
Improved the error messages.  The original message for checking for valid range would output something that didn't make sense or at least wasn't helpful.  Split this into two checks and output info that helps locate problem.
Added `connectname` to error messages to show which connection had issues.
The transform check was testing `abs(transform[i]) < 0` which isn't possible.  It should be `<=0` or `<1`
> Improve error messages, fix error check

- src/cgnslib.c
Reverts CGNS/CGNS#62
Via Mark,
Fortunately, I just spent most of April refactoring some 1-to-1 connection logic in our code (ala CGNS), and so, I was able to see that #62 breaks/violates the CGNS SIDS.
The “transform” for 1:1 connections is allowed to be 0 in null (singleton) dimensions.  Section 8.1 of the SIDS:
http://cgns.github.io/CGNS_docs_current/sids/cnct.html#GridConnectivity1to1
Says the following:
For establishing relationships between adjacent and current zone indices lying on the interface itself, one of the elements of Transform is superfluous since one component of both interface indices remains constant. It is therefore acceptable to set that element of Transform to zero.
The new check in #63 on line 5837 is not allowing abs(transform)==0, thereby violating the above …
> Revert "Improve error messages, fix error check"

- src/cgnslib.c
Improved the error messages.  The original message for checking for valid range would output something that didn't make sense or at least wasn't helpful.  Split this into two checks and output info that helps locate problem.
Added `connectname` to error messages to show which connection had issues.
The transform check was testing `abs(transform[i]) < 0` which isn't possible so that can be removed.  Note that transform[i] can be equal to zero in the null dimension which wasn't recognized in the original pull request.
This was originally submitted as #62 which was applied and then reverted by #63.  Issues identified in #63 have been addressed in this revision.
> Improve error messages, fix error check (fixed)

- src/cgnstools/utilities/cgnsImport.c
An if test is using `=` instead of `==`
> Fix bad if test --

- appveyor.yml
Reported at https://cgnsorg.atlassian.net/projects/CGNS/issues/CGNS-145
See also: https://github.com/CGNS/CGNS/commit/59d88143513fcd6fd7eac56d5a39df5cc022b618#r30513524
TL;DR: AppVeyor build matrix was not being exercised, wrong variable was being dereferenced
> Test AppVeyor matrix correctly

- src/pcgnslib.c
I ran into a problem where CGNS with parallel support would not build on Windows (using MS-MPI and parallel HDF5), because 'variable length arrays' are not supported in Visual C. Therefore, these have been replaced with malloc/free version to fix this problem.
> Build parallel CGNS on Windows

- src/cg_ftoc.c
- src/cgns_internals.c
- src/cgnslib.c
- src/tests/test_general_rind.c
- src/tests/test_general_rindf.F
Following the removal of grid number as a  parameter for cg_coord_general_xxx, tests were failing.
As a side note, deforming meshes using multiple GridCoordinates nodes won't be readable or writable with rind planes with the new API since cg_array_general_read/write is not aware of Rind Indexing thus always falling back to a CG_CONFIG_RIND_ZERO state (as it was done before).
> Fix broken test with Rind Plane Indexing

- CMakeLists.txt
On Mac OSX, (Darwin), I think that this is needed for proper RPATH handling.  I have been manually setting this in my builds on Mac, but I think it should be handled automatically in the CGNS CMakeLists.txt...
> RPATH handling for MacOSX (Darwin)

- src/CMakeLists.txt
* CGNS-146 :: Can't compile using MSVC & IVF on windows (MSVS 14)
Explicitly set the CMake `LINKER_LANGUAGE` property on `cngs_static` to `C`.
This is a work around for a potential CMake bug, and was suggested by
@bradking. Here is the issue and merge that introduced the bug:
- https://gitlab.kitware.com/cmake/cmake/issues/16738
- https://gitlab.kitware.com/cmake/cmake/merge_requests/643
> CGNS-146 (#87)

- src/cgns_internals.c
The variable `n` is used as an index in an outer and inner loop.  Use different index for inner loop.
> Eliminate use of variable in two nested loops

- src/pcgnslib.c
Eliminate for loops of the form `for (int n=....` . In this case, the only change needed is to remove the `int` since `n` is already declared in the routines and the `int n` is just causing a shadowing of the previously defined `n`.  Also eliminates need to use C99 or later standard when compiling.
> Eliminate C99 style for loop -- unneeded

- src/cgns_io.c
- src/tests/ser_benchmark_hdf5.c
Allows library and tests to compile using some variant of iso C.  S_IFREG and M_PI are not accessible unless _XOPEN_SOURCE >= 500.  This does not modify an existing definition of _XOPEN_SOURCE.
> Support for std C on linux

- src/adfh/ADFH.c
The check for open files was summing the `g_files` entry when all that was needed was a yes/no on whether there were any open files.  Depending of the value of `g_files` it was possible for the integer sum to overflow the range of a signed int which gives undefined behavior.  `idx` is an integer and `g_files` is an `hid_t` which is 64-bits on recent HDF5 versions, so overflow is definitely a possibility (and has happened in the wild)
> Eliminate potential integer overflow / undefined behavior

- src/CMakeLists.txt
In the current CMake build, the `${CMAKE_CURRENT_BINARY_DIR}` include is the last one on the compilation line.  This directory contains the most up-to-date version of the `cgnstypes.h` include file.  If there is another version of `cgnstypes.h` existing in an install directory, perhaps the same directory containing hdf5 or some other include files, then the older `cgnstypes.h` will be included instead of the more current one.    Here is an example of the include specifications for the PATCHED and ORIGINAL compilation commands:
```
ORIGINAL:
cd /gpfs1/cgns/CGNS/build/src && mpicc 
-I/gpfs1/install_dir/include 
-I/gpfs1/cgns/CGNS/src 
-I/gpfs1/cgns/CGNS/build/src  
-I/gpfs1/install_dir/include 
PATCHED:
cd /gpfs1/cgns/CGNS/build/src && mpicc 
-I/gpfs1/cgns/CGNS/build/src …
```
> Order include directives to get correct includes

- src/adfh/ADFH.c
If CGNS is built against the new HDF5-1.10.x library versions, the files that are created are not readable by applications which are built against earlier HDF5-1.8.x library versions.  This can cause issues on many systems which are using commercial or externally maintained visualization or other applications (ParaView, Ensight, ...) . 
Adding the command to use the `H5F_LIBVER_V18` option makes the files readable by the older applications.  
Here is some advice from the HDF5 group related to this issue:
```
If an application written for 1.8.* is linked with HDF5 1.10.(i.e., it doesn’t use any new features of 1.10.0), a file created by the application will be readable by HDF5 1.8. (or even earlier versions). The exception to this rule would be an application that uses H5Pset_libver_bounds …
```
> Create hdf5-1.8.x compatible files from 1.10.X library

- src/cgns_io.c
On OSX, the XOPEN version needs to be at least 600 to include the function prototype for `readlink` using the following compiler:
```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
```
The warning is:
```
/Users/gdsjaar/src/seacas/TPL/cgns/CGNS/src/cgns_io.c:229:15: warning: implicit declaration of function 'readlink' is invalid in C99
[-Wimplicit-function-declaration]
len = readlink(filename, linkfile, st.st_size + 1);
^
```
When `_XOPEN_SOURCE` is defined to be 500.  Warning goes away when defined to be 600.  
This also happens with gcc-8.3.0 on OSX.
> Fix for OSX Build

- src/Test_UserGuideCode/C_code_parallel/write_grid_str_parinzone.c
- src/Test_UserGuideCode/C_code_parallel/write_grid_str_paroverzone.c
- src/ptests/test_general_readwrite.c
There are a few uses of CGNS Enums which were not wrapped by the `CGNS_ENUMV()` macro. Fixed so now tests will build with `CG_SCOPED_ENUMS` defined.
> Fix tests for scoped enum use

- src/cgns_internals.c
In cgi_read_ptset there is made a difference between point set of list and range type.
The 'CellListDonor' type was missing in the list of list types and this led to a heap buffer overflow.
Added 'CellListDonor' type to list of list types.
Fixes issue CGNS-158
> Fix heap buffer overflow in cgi_read_ptset

- src/adf/ADF_internals.c
Add a search loop for an early NULL termination of the string passed to ADFI_string_2_C_string in order to prevent global-buffer-overflow when string literals are given as a parameter.
Fixes issue CGNS-159.
> Fix global-buffer-overflow in ADFI_string_2_C_string.

- src/configure
- src/configure.ac
If the CGNS is configured with `configure --prefix=somedir` then `make install` fails with the error
> ----- cgnsview -----
> Making directory /share
> mkdir: cannot create directory ‘/share’: Permission denied
This is because the path variable remains unexpanded in src/cgnstools/make.defs: `LIB_INSTALL_DIR = ${prefix}/share`
This PR fixes the issue.
> Fix cgnstools install

- src/cgnslib.c
To reduce memory usage of cg_ElementPartialSize only load ElementStartOffset array and compute ElementDataSize from it
> Do not read elements when computing partial data size

- src/cgns_internals.c
Minor fix; only applicable if more than 2.1 billion intervals in a range, but does eliminate a compiler warning -- `npt` should be `cgsize_t`
> Fix incorrect variable type

- src/adfh/ADFH.c
A few variables defined as `int` should be `ssize_t` to avoid potential loss of data on large models.
> Fix compiler warnings about possible loss of data

- src/adf/ADF_interface.c
- src/cgns_io.c
on travis two warnings keep appearing, this commit remove them
> remove warning from -Wunused-result

- CMakeLists.txt
When not using shared libraries, do not do anything with RPATH on the
executables.
> CMakeLists.txt: Disable RPATH setting if not using shared

- CMakeLists.txt
I think that the correct symbol to test should be `CGNS_BUILD_SHARED` instead of `CGNS_USE_SHARED`
With the test as it currently exists, my builds are not getting the correct rpath during the install of the tools (cgnsidff, cgnslist, ...), but if I use `CGNS_BUILD_SHARED`, then everything seems to work correctly and i get the correct rpath on the tools.  The `make install` step also shows that CMake is adding the runtime path to the installed tools, but I don't get the message with the current symbol in the test.  (The message is `Set runtime path of ...` during the install phase)
> Change shared build rpath test symbol

- CMakeLists.txt
Nowadays Hdf5 requires cmake 3.12. Thus a little upgrade to require at least a 3.8 version of cmake in CGNS library seems sane.
> Upgrade minimum required version for cmake

- src/Test_UserGuideCode/C_code/read_discreteface_str.c
- src/adfh/ADFH.c
- src/cgnslib.c
- src/cgnstools/cgnsview/cgnsview.bat
- src/cgnstools/cgnsview/cgnsview.sh
- src/tests/test_family_treef.F90
- Add environment variable to prevent cgnsview from locking CGNS/HDF5 files and let other tools like cgnscheck do their job
- Comment unlink in fortran test that creates problem on some platforms
- Rewrite initialization of stack array to remove GCC warning
- Add some missing CGNS library versions.
- Add a strcpy to prevent overflow with label shorter than ADF_NAME_LENGTH. (Internally it seems that label attribute has a fixed size of same length as the name attribute.)
> Small improvements

- src/cgns_f.F90
Fortran API: Correct double !! comment, otherwise OMP compilers get confused.
> Fortran API: Correct double !! comment

- src/cgns_io.c
cgio_copy_node() fails with INVALID_DATA_TYPE error when HDF5 backend is employed
> Fix cgio_copy_node()

- src/configure
- src/configure.ac
`./configure` script provides two identically named options `--enable-scope` for setting different flags CG_BUILD_SCOPE & CG_BUILD_BASESCOPE. Add `--enable-basescope` for the latter.
> Fix configuration of base scoping

- src/tools/cgnscheck.c
This is a small improvement patch for cgnscheck.
It advertises when a BC should be of type FamilySpecified (ie when a FamilyName is found).
> Add a warning for BC that should be of type FamilySpecified.

- src/adfh/ADFH.c
Was testing some file-open scaling behavior and wanted to see if the code in the `#ifdef JFC_PATCH_2015_2` blocks made any difference, but the creation of `g_propfileopen` was in the wrong place.
There is also an issue with `tconv` and `bkg` being shadowed in the later call at line 2253 but that is not fixed here...
> Fix so will compile with JFC_PATCH_2015_2 enabled

- src/ptests/test_poly_unstructured.c
when cgsize_t is 32bit the MPI_Allgather was not sending correct data.
> fix MPI_Allgather in test_poly_unstructured

- CMakeLists.txt
INTEGER is not valid anymore, see : https://cmake.org/cmake/help/latest/command/set.html?highlight=set#set-cache-entry
> clear cmake warning

- src/tools/cgnscheck.c
Add check on node names accroding to SIDS (check that dot and slash are not at the start of name, see:https://cgns.github.io/CGNS_docs_current/hdf5/general.html)
Add warning if ZoneBC_t is missing while zone surface are present in a 3D mesh.
> Improve cgnscheck

- src/tools/cgnscheck.c
It corrects a mismatch between the type and the number of points of selected element for MIXED section.
> fix cgnscheck warning CGNS-234

- src/cgns_internals.c
use memcpy instead of strcpy and skip costly string copy when name will not move
> small tuning

- CMakeLists.txt
The CGNS_VERSION is read from src/cgnslib.h
The same logic is used by autotools.
When changing version only modification in one place - cgnslib.h - is needed reducing mismatch errors.
> update CMake logic to get CGNS_VERSION

- src/cg_ftoc.c
- src/cgns_f.F90
- src/cgns_fortrandll.def.in
- src/ptests/pcgns_ftest.F90
- src/tests/cgwrite_f03.F90
- src/tests/test_core_vfd.c
With some fortran compiler, cgwrite_f03 is failing.
Indeed the fortran to C mapping does not go well and a (void **) was transfered thus value_c did not get the right value (the set value in value_c was the pointer address). By explicitly casting the whole chain, it solves the issue.
Furthermore value_f is declared as "cgsize_t" while "int" is used inside the C code. (In particular, we have ((int)(size_t)file_type) ...
Changing between 64bit and 32bit compilation generates also a failed test.
> fix fortran failure

- src/ptests/Metadata_Stressing.c
The `uint` cast should be `uint32_t`
> Fix bad cast

- src/examples/fortran/Test1/cgmodify.F90
- src/examples/fortran/Test_PartRdWr/cgwrite.F90
- src/examples/fortran/Test_mixed_elements/cgmodify.F90
- src/examples/fortran/Test_mixed_elements/cgwrite.F90
- src/examples/fortran/Test_mixed_grid/cgmodify.F90
- src/examples/fortran/Test_mixed_grid/cgwrite.F90
- src/examples/fortran/Test_motion/cgwrite.F90
- src/ptests/fexample.F90
Fixed typo in fexample_f and removed warnings reported due to number DO loops. CGNS-249
> CGNS-249 clean-up, fixed typo and removed remaining numbered DO loops

- src/CMakeLists.txt
For windows platforms we only need to rename the shared library when the import library name is the same as the static name
With msvc this is usually the case (cgns.lib) but not on mingw where libcgns.a and libcgns.dll.a can coexist.
> Keep default library name on mingw

- src/cgns_io.c
- src/cgnstypes.h.in
- src/tools/cgnscompress.c
This conflicts with `struct stat` that comes in `sys/stat.h` header with
MSVC. Older compilers may have other things, but it is just not valid to
do it without more sophisticated checks.
> cgnstypes: avoid defining `stat`

- src/pcgnslib.c
As the comment states, `m_dimvals[:]` should be `0`. However, the argument passed to `H5Screate_simple()` is `dimvals`, which is an uninitialised local array.
> Copy `m_dimvals` to `dimvals`.

- src/cgns_io.c
- src/cgnslib.c
Currently, the default file_type is set prior to calling **cgio_open_file** from **cg_open** if cgns_filetype has not been specified. This leads to the error message "cgio_open_file:not a HDF5 file - required for parallel" when an ADF based file is opened and the CGNS library has been compiled with support for HDF5 and parallel output.
By now only setting the default file_type when a new file is to be created within cgio_open_file, we can avoid the above problem without changing the default behavior of the code.
Moving the setting of the file_type into cgio_open_file breaks some of the tests that explicitly call this routine. So now, just limit the default initialization of file_type within cg_open to when a new file is to be created.
ref. CGNS-266
> Set the default file_type in cg_open only when in write mode

- src/adf/ADF_internals.h
- src/cg_malloc.c
- src/cg_malloc.h
- src/cgns_header.h
- src/cgns_io.h
- src/tests/test_complex.c
- src/tests/test_ver31.c
- src/tests/write_test.c
Clang is considering making this warning an error by default: https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521
> Fixed clang -Wstrict-prototypes warnings

- src/tools/cgnscheck.c
The new algorithm uses a hash to speed up the check.
It allows to not spend too much time when the file is correct.
> More efficient check for duplicate faces

- src/adfh/ADFH.c
Increase the maximum open file limit to 1024 which is a typical value for many operating systems.  Since some OS's have higher or lower limits, it would be nice to make this configurable at some point, but a hardwired value of 1024 fixes the main issue that I am seeing right now...
> Increase maximum open file limit

- src/adfh/ADFH.c
Newer HDF5 builds can still choose to have old ABIs.
> ADFH: check for the H5L info structure type directly

- CMakeLists.txt
- src/CMakeLists.txt
- src/cgns-config.cmake.in
This adds a cgns-config.cmake file to allow projects to use find_package(cgns).
It also adjust names of hdf5 libraries to link with to use names given by find_package(HDF5).
> Add cgns-config.cmake file.

- src/cgnslib.c
Only data arrays are forced to be contiguous in the Elements_t node.
> Do not force Elements_t node to be contiguous

- .github/workflows/codeql.yml
- .github/workflows/config-cgns.sh
- .github/workflows/main.yml
- CMakeLists.txt
- appveyor.yml
- src/fortran_macros.h
- src/tests/test_general_reshape.c
- Update cmake requirement to be coherent with hdf5.
This could also help with packaging on the long run.
- Fix Fortran to C mapping on Apple ARM64
This is compiler dependent so a better design based on ISO C should be possible.
The current correction is based on https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gfortran.pdf  (see hidden parameter section)
> Update cmake requirement

- src/tools/cgnscheck.c
Hi,
this branch includes improvements of cgnscheck:
- check all GridCoordinates_t nodes
- allow "Null" keywords for *Pointers
> [cgnscheck] check multiple gridcoordinates nodes & nullpointer

- src/ptests/Makefile.in
- src/ptests/test_poly_unstructured.c
- src/ptests/test_poly_unstructured_f90.F90
Fixed assumption that cgsize_t is always integer*8 in test, added missing test for autotools.
> Fixed cgsize_t type for MPI calls in test

- src/ptests/test_poly_unstructured.c
Since the mpi arguments are long, use MPI_LONG as the type. This fixes failures when cgsize_t is an int.
> fixed type for MPI_Allgather

- src/CMakeLists.txt
- src/cgns_header.h
- src/tests/CMakeLists.txt
Some small fixes:
- be more robust to multiconfiguration cmake generators
- fix ctest path on windows
- remove redefinition of a macro
> Misc windows fixes

- src/adfh/ADFH.c
- src/cgns_io.c
From the man page for `access()`:
> Use of these functions is discouraged since by the time the returned information is acted upon, it  is  out-of-date.  (That is, acting upon the information always leads to a time-of-check-to-time-of-use race condition.) An application should instead attempt the action itself and handle the [EACCES] error that occurs if the file is not accessible
We've run into these race conditions on a few different file systems now, where when trying to write a file in parallel from a large number of parts we get 
```
CGNS error 1 cgio_open_file:File Open Error: NEW - File already exists
```
I think this is particularly prevalent on "performance" file-systems which are often not POSIX compliant. Though technically these race conditions could happen in serial too.
I've …
> Remove `access()` calls

- .github/workflows/intel.yml
- .github/workflows/scripts/README.md
- .github/workflows/scripts/build_linux.sh
- .github/workflows/scripts/cache_exclude_linux.sh
- .github/workflows/scripts/cache_exclude_windows.sh
- .github/workflows/scripts/install_linux.sh
- .github/workflows/scripts/install_windows.bat
This at least gets us some Windows testing of serial CGNS build with Intel OneAPI, Fortran, and Shared.
I updated cgsn263 for Intel 2025 and the latest HDF5 release.
The Intel Linux builds, but since it does not test CGNS, I commented it out.
Related to #313
> Added Intel Windows CI testing with Fortran
